name: QA

on:
    pull_request:
        branches:
            - release/*

jobs:
    backend:
        runs-on: ubuntu-18.04
        steps:
            -   uses: actions/checkout@v2

            # https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: '7.1'
                    coverage: none # disable xdebug, pcov

            -   run: composer validate --strict
            -   run: composer config -g github-oauth.github.com ${{ secrets.COMPOSER_ZICHTONLINE_TOKEN }}
            -   run: composer install --prefer-dist --no-progress --no-suggest --no-scripts
            -   if: always()
                run: composer run-script lint
